### ISSUE TITLE
Nashorn support

### ISSUE THREAD

**Issue by benmccann** [typesafehub/js-engine#32]
I see that Rhino is an option. It'd also be nice to have Nashorn be an option since it's supposed to be so much more performant for those users on Java 8.

**Comment by fernandezpablo85** [comment]
@huntc @benmccann is anyone working on this? I'm working on a typescript plugin for sbt and nashorn support would be fantastic!

I don't mind working on the PR, just wanted to check if there was work in progress already.

**Comment by benmccann** [comment]
@fernandezpablo85 check out @huntc's first comment. he closed this because nashorn is already supported. maybe i'm missing something and there's something else you're looking to be supported still?

**Comment by fernandezpablo85** [comment]
yeah maybe the support un sbt-js-engine.  I've created a ticket there and
referenced this one.
