### ISSUE TITLE
Rename JavaxEngine to just Javax?

### ISSUE THREAD

**Issue by benmccann** [typesafehub/js-engine#34]
None of the other engines have the word engine in the name, so perhaps we want to remove it from JavaxEngine to make them analagous?

**Comment by huntc** [comment]
The problem is that javax refers to many things, and can indeed refer to Rhino or Nashorn depending on the version of the JDK. I think it may be relevant here. WDYT?

**Comment by benmccann** [comment]
I don't have any strong opinion. As long as it was done on purpose. I just wanted to make sure to raise the issue since I believe the javax one was community contributed and perhaps it just slipped by code review

**Comment by huntc** [comment]
Thanks Ben.
