### ISSUE TITLE
Combine Rhino and Javax engines?

### ISSUE THREAD

**Issue by benmccann** [typesafehub/js-engine#35]
Rhino is just one case of Javax, right?. If you use Javax and are on Java 7 then you get Rhino and if you're on Java 8 then you get Nashorn. It'd be nice to deprecate Rhino and just use Javax so that folks who are on Java 8 get Nashorn.

**Comment by huntc** [comment]
Rhino offers a distinct set of APIs to Javax. The Javax APIs are higher level.
