### ISSUE TITLE
Release 1.1.2

### ISSUE THREAD

**Issue by benmccann** [typesafehub/js-engine#42]
@huntc would you be able to cut a release?  I'd really love to use the Java 8 fix as well as @yanns fix https://github.com/typesafehub/js-engine/commit/e8ce70ef2b42de2ba2d81aef54c88a6285eba0ee

**Comment by huntc** [comment]
I just tried releasing and I'm getting the following problem reported:

```
[info] downloading https://repo1.maven.org/maven2/io/spray/spray-json_2.11/1.3.2/spray-json_2.11-1.3.2.jar ...
[warn] 	[FAILED     ] io.spray#spray-json_2.11;1.3.2!spray-json_2.11.jar(bundle): SSL peer shut down incorrectly (115840ms)
[warn] 	[FAILED     ] io.spray#spray-json_2.11;1.3.2!spray-json_2.11.jar(bundle):  (0ms)
```

I'm overseas at present, and the network could be flaky. I can try again tomorrow when I get home - unless @jroper has a chance to do it.

**Comment by benmccann** [comment]
Done. Thanks @jroper !
