### ISSUE TITLE
Improper shutdown causing test flakiness

### ISSUE THREAD

**Issue by benmccann** [typesafehub/js-engine#50]
See details on mailing list: https://groups.google.com/forum/?fromgroups#!topic/play-framework-dev/uDZXv9_p0S4

**Comment by dwijnand** [comment]
This is still an issue, and it just broke my PR https://github.com/typesafehub/js-engine/pull/60...

Along with the chat in that ML thread, there's some in https://github.com/typesafehub/js-engine/pull/51 too.
