### ISSUE TITLE
Scala 2.12 version

### ISSUE THREAD

**Issue by driverpt** [typesafehub/js-engine#52]
As title says.

**Comment by benmccann** [comment]
Scala 2.11 should already be supported

Supporting Scala 2.12 would be difficult. This is used by sbt-js-engine and SBT plugins are built only for Scala 2.10. Most of the dependencies do not support both Scala 2.10 and 2.12

**Comment by jroper** [comment]
js-engine 1.2.3 has been released with cross build against Scala 2.12.
