### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by benmccann** [typesafehub/js-engine#55]
@huntc @wsargent would you be able to release a new version?

I tried, but it seems I don't have access

java.io.IOException: Access to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/com/typesafe/jse_2.10/1.2.1/jse_2.10-1.2.1-javadoc.jar.asc was refused by the server: Forbidden

**Comment by marcospereira** [comment]
Hey @benmccann,

Can this wait until next Friday release train?

**Comment by benmccann** [comment]
Sure. I'm not in a huge rush. I'd just like to get it out in time that I can make the npm project use it before Play 2.6

**Comment by gmethvin** [comment]
Released 1.2.1

**Comment by benmccann** [comment]
Thanks!!
