### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by benmccann** [typesafehub/js-engine#57]
@gmethvin @wsargent would you be able to cut a new version?

**Comment by benmccann** [comment]
@mkurz I'm assuming you don't have access to release?

**Comment by mkurz** [comment]
@benmccann No

**Comment by wsargent** [comment]
@benmccann I can do it.

**Comment by wsargent** [comment]
@benmccann  1.2.2 or 1.3.0?

**Comment by mkurz** [comment]
I think 1.2.2 should be enough because if you look at the master branch only one commit got reverted.

**Comment by benmccann** [comment]
Yeah, 1.2.2

**Comment by wsargent** [comment]
Done.

**Comment by benmccann** [comment]
Thanks!!
